// Secteur 1 — arrondissement de Béziers (153 communes, dont Cap d'Agde et
// Le Grau-d'Agde, quartiers d'Agde à fort volume de recherche locale).
export const COMMUNES = [
  { name: 'Abeilhan', slug: 'abeilhan' },
  { name: 'Adissan', slug: 'adissan' },
  { name: 'Agde', slug: 'agde' },
  { name: 'Agel', slug: 'agel' },
  { name: 'Aigne', slug: 'aigne' },
  { name: 'Aigues-Vives', slug: 'aigues-vives' },
  { name: 'Les Aires', slug: 'les-aires' },
  { name: 'Alignan-du-Vent', slug: 'alignan-du-vent' },
  { name: 'Assignan', slug: 'assignan' },
  { name: 'Aumes', slug: 'aumes' },
  { name: 'Autignac', slug: 'autignac' },
  { name: 'Azillanet', slug: 'azillanet' },
  { name: 'Babeau-Bouldoux', slug: 'babeau-bouldoux' },
  { name: 'Bassan', slug: 'bassan' },
  { name: 'Beaufort', slug: 'beaufort' },
  { name: 'Berlou', slug: 'berlou' },
  { name: 'Bessan', slug: 'bessan' },
  { name: 'Boisset', slug: 'boisset' },
  { name: 'Boujan-sur-Libron', slug: 'boujan-sur-libron' },
  { name: 'Bédarieux', slug: 'bedarieux' },
  { name: 'Béziers', slug: 'beziers' },
  { name: 'Cabrerolles', slug: 'cabrerolles' },
  { name: 'Cabrières', slug: 'cabrieres' },
  { name: 'Cambon-et-Salvergues', slug: 'cambon-et-salvergues' },
  { name: 'Camplong', slug: 'camplong' },
  { name: "Cap d'Agde", slug: 'cap-d-agde' },
  { name: 'Capestang', slug: 'capestang' },
  { name: 'Carlencas-et-Levas', slug: 'carlencas-et-levas' },
  { name: 'Cassagnoles', slug: 'cassagnoles' },
  { name: 'Castanet-le-Haut', slug: 'castanet-le-haut' },
  { name: 'Castelnau-de-Guers', slug: 'castelnau-de-guers' },
  { name: 'La Caunette', slug: 'la-caunette' },
  { name: 'Causses-et-Veyran', slug: 'causses-et-veyran' },
  { name: 'Caussiniojouls', slug: 'caussiniojouls' },
  { name: 'Caux', slug: 'caux' },
  { name: 'Cazedarnes', slug: 'cazedarnes' },
  { name: "Cazouls-d'Hérault", slug: 'cazouls-d-herault' },
  { name: 'Cazouls-lès-Béziers', slug: 'cazouls-les-beziers' },
  { name: 'Cers', slug: 'cers' },
  { name: 'Cessenon-sur-Orb', slug: 'cessenon-sur-orb' },
  { name: 'Cesseras', slug: 'cesseras' },
  { name: 'Colombiers', slug: 'colombiers' },
  { name: 'Colombières-sur-Orb', slug: 'colombieres-sur-orb' },
  { name: 'Combes', slug: 'combes' },
  { name: 'Corneilhan', slug: 'corneilhan' },
  { name: 'Coulobres', slug: 'coulobres' },
  { name: 'Courniou', slug: 'courniou' },
  { name: 'Creissan', slug: 'creissan' },
  { name: 'Cruzy', slug: 'cruzy' },
  { name: 'Cébazan', slug: 'cebazan' },
  { name: 'Espondeilhan', slug: 'espondeilhan' },
  { name: 'Faugères', slug: 'faugeres' },
  { name: 'Ferrals-les-Montagnes', slug: 'ferrals-les-montagnes' },
  { name: 'Ferrières-Poussarou', slug: 'ferrieres-poussarou' },
  { name: 'Florensac', slug: 'florensac' },
  { name: 'Fontès', slug: 'fontes' },
  { name: 'Fos', slug: 'fos' },
  { name: 'Fouzilhon', slug: 'fouzilhon' },
  { name: 'Fraisse-sur-Agout', slug: 'fraisse-sur-agout' },
  { name: 'Félines-Minervois', slug: 'felines-minervois' },
  { name: 'Gabian', slug: 'gabian' },
  { name: 'Graissessac', slug: 'graissessac' },
  { name: "Le Grau-d'Agde", slug: 'le-grau-d-agde' },
  { name: 'Hérépian', slug: 'herepian' },
  { name: 'Lamalou-les-Bains', slug: 'lamalou-les-bains' },
  { name: 'Laurens', slug: 'laurens' },
  { name: 'Lespignan', slug: 'lespignan' },
  { name: 'Lieuran-Cabrières', slug: 'lieuran-cabrieres' },
  { name: 'Lieuran-lès-Béziers', slug: 'lieuran-les-beziers' },
  { name: 'Lignan-sur-Orb', slug: 'lignan-sur-orb' },
  { name: 'La Livinière', slug: 'la-liviniere' },
  { name: 'Lézignan-la-Cèbe', slug: 'lezignan-la-cebe' },
  { name: 'Magalas', slug: 'magalas' },
  { name: 'Maraussan', slug: 'maraussan' },
  { name: 'Margon', slug: 'margon' },
  { name: 'Marseillan', slug: 'marseillan' },
  { name: 'Maureilhan', slug: 'maureilhan' },
  { name: 'Minerve', slug: 'minerve' },
  { name: 'Mons', slug: 'mons' },
  { name: 'Montady', slug: 'montady' },
  { name: 'Montagnac', slug: 'montagnac' },
  { name: 'Montblanc', slug: 'montblanc' },
  { name: 'Montels', slug: 'montels' },
  { name: 'Montesquieu', slug: 'montesquieu' },
  { name: 'Montouliers', slug: 'montouliers' },
  { name: 'Murviel-lès-Béziers', slug: 'murviel-les-beziers' },
  { name: 'Neffiès', slug: 'neffies' },
  { name: 'Nissan-lez-Enserune', slug: 'nissan-lez-enserune' },
  { name: 'Nizas', slug: 'nizas' },
  { name: "Nézignan-l'Évêque", slug: 'nezignan-l-eveque' },
  { name: 'Olargues', slug: 'olargues' },
  { name: 'Olonzac', slug: 'olonzac' },
  { name: 'Oupia', slug: 'oupia' },
  { name: 'Pailhès', slug: 'pailhes' },
  { name: 'Pardailhan', slug: 'pardailhan' },
  { name: 'Pierrerue', slug: 'pierrerue' },
  { name: 'Pinet', slug: 'pinet' },
  { name: 'Poilhes', slug: 'poilhes' },
  { name: 'Pomérols', slug: 'pomerols' },
  { name: 'Portiragnes', slug: 'portiragnes' },
  { name: 'Le Poujol-sur-Orb', slug: 'le-poujol-sur-orb' },
  { name: 'Pouzolles', slug: 'pouzolles' },
  { name: 'Le Pradal', slug: 'le-pradal' },
  { name: 'Prades-sur-Vernazobre', slug: 'prades-sur-vernazobre' },
  { name: 'Prémian', slug: 'premian' },
  { name: 'Puimisson', slug: 'puimisson' },
  { name: 'Puissalicon', slug: 'puissalicon' },
  { name: 'Puisserguier', slug: 'puisserguier' },
  { name: 'Péret', slug: 'peret' },
  { name: 'Pézenas', slug: 'pezenas' },
  { name: 'Pézènes-les-Mines', slug: 'pezenes-les-mines' },
  { name: 'Quarante', slug: 'quarante' },
  { name: 'Rieussec', slug: 'rieussec' },
  { name: 'Riols', slug: 'riols' },
  { name: 'Roquebrun', slug: 'roquebrun' },
  { name: 'Roquessels', slug: 'roquessels' },
  { name: 'Rosis', slug: 'rosis' },
  { name: 'Roujan', slug: 'roujan' },
  { name: 'Saint-Chinian', slug: 'saint-chinian' },
  { name: 'Saint-Geniès-de-Fontedit', slug: 'saint-genies-de-fontedit' },
  { name: 'Saint-Geniès-de-Varensal', slug: 'saint-genies-de-varensal' },
  { name: 'Saint-Gervais-sur-Mare', slug: 'saint-gervais-sur-mare' },
  { name: 'Saint-Jean-de-Minervois', slug: 'saint-jean-de-minervois' },
  { name: 'Saint-Julien', slug: 'saint-julien' },
  { name: "Saint-Martin-de-l'Arçon", slug: 'saint-martin-de-l-arcon' },
  { name: 'Saint-Nazaire-de-Ladarez', slug: 'saint-nazaire-de-ladarez' },
  { name: 'Saint-Pons-de-Mauchiens', slug: 'saint-pons-de-mauchiens' },
  { name: 'Saint-Pons-de-Thomières', slug: 'saint-pons-de-thomieres' },
  { name: 'Saint-Thibéry', slug: 'saint-thibery' },
  { name: "Saint-Vincent-d'Olargues", slug: 'saint-vincent-d-olargues' },
  { name: 'Saint-Étienne-Estréchoux', slug: 'saint-etienne-estrechoux' },
  { name: "Saint-Étienne-d'Albagnan", slug: 'saint-etienne-d-albagnan' },
  { name: 'La Salvetat-sur-Agout', slug: 'la-salvetat-sur-agout' },
  { name: 'Sauvian', slug: 'sauvian' },
  { name: 'Servian', slug: 'servian' },
  { name: 'Siran', slug: 'siran' },
  { name: 'Le Soulié', slug: 'le-soulie' },
  { name: 'Sérignan', slug: 'serignan' },
  { name: 'Taussac-la-Billière', slug: 'taussac-la-billiere' },
  { name: 'Thézan-lès-Béziers', slug: 'thezan-les-beziers' },
  { name: 'La Tour-sur-Orb', slug: 'la-tour-sur-orb' },
  { name: 'Tourbes', slug: 'tourbes' },
  { name: "Usclas-d'Hérault", slug: 'usclas-d-herault' },
  { name: 'Valras-Plage', slug: 'valras-plage' },
  { name: 'Valros', slug: 'valros' },
  { name: 'Vendres', slug: 'vendres' },
  { name: 'Verreries-de-Moussans', slug: 'verreries-de-moussans' },
  { name: 'Vias', slug: 'vias' },
  { name: 'Vieussan', slug: 'vieussan' },
  { name: "Villemagne-l'Argentière", slug: 'villemagne-l-argentiere' },
  { name: 'Villeneuve-lès-Béziers', slug: 'villeneuve-les-beziers' },
  { name: 'Villespassans', slug: 'villespassans' },
  { name: 'Vélieux', slug: 'velieux' },
];

export const COMMUNES_BY_SLUG = Object.fromEntries(COMMUNES.map((c) => [c.slug, c]));
