// Search terms ("métiers") combined with communes.js to generate local SEO
// landing pages at /[metier]/[commune]. Each entry is grounded in a real
// prestation or category Services 34 actually offers — either reusing an
// existing detail page's title (parentHref points straight at it) or a
// common job-title synonym that funnels back to the closest real prestation
// or, failing that, the category page itself.
const P = (term, slug, category, categoryLabel, parentHref) => ({ term, slug, category, categoryLabel, parentHref });

export const METIERS = [
  // --- Bricolage : les 16 prestations existantes ---
  P('Montage de meubles', 'montage-de-meubles', 'bricolage', 'Bricolage', '/bricolage/montage-de-meubles'),
  P('Assemblage de meubles IKEA', 'assemblage-ikea', 'bricolage', 'Bricolage', '/bricolage/assemblage-ikea'),
  P("Fixation d'étagères", 'fixation-etageres', 'bricolage', 'Bricolage', '/bricolage/fixation-etageres'),
  P('Accrocher un tableau ou un miroir', 'accrocher-tableau-miroir', 'bricolage', 'Bricolage', '/bricolage/accrocher-tableau-miroir'),
  P('Pose de tringles à rideaux', 'pose-tringles-rideaux', 'bricolage', 'Bricolage', '/bricolage/pose-tringles-rideaux'),
  P('Remplacer une porte ou une poignée', 'remplacer-porte-poignee', 'bricolage', 'Bricolage', '/bricolage/remplacer-porte-poignee'),
  P('Pose de crédence', 'pose-credence', 'bricolage', 'Bricolage', '/bricolage/pose-credence'),
  P('Peinture intérieure', 'peinture-interieure', 'bricolage', 'Bricolage', '/bricolage/peinture-interieure'),
  P('Pose de papier peint', 'pose-papier-peint', 'bricolage', 'Bricolage', '/bricolage/pose-papier-peint'),
  P('Boucher un trou, enduire un mur', 'boucher-trou-enduire-mur', 'bricolage', 'Bricolage', '/bricolage/boucher-trou-enduire-mur'),
  P("Petits travaux d'électricité", 'petits-travaux-electricite', 'bricolage', 'Bricolage', '/bricolage/petits-travaux-electricite'),
  P('Petits travaux de plomberie', 'petits-travaux-plomberie', 'bricolage', 'Bricolage', '/bricolage/petits-travaux-plomberie'),
  P('Installation électroménager', 'installation-electromenager', 'bricolage', 'Bricolage', '/bricolage/installation-electromenager'),
  P('Serrurerie', 'serrurerie', 'bricolage', 'Bricolage', '/bricolage/serrurerie'),
  P('Isolation de porte ou fenêtre', 'isolation-porte-fenetre', 'bricolage', 'Bricolage', '/bricolage/isolation-porte-fenetre'),
  P('Petites réparations diverses', 'petites-reparations', 'bricolage', 'Bricolage', '/bricolage/petites-reparations'),
  // --- Bricolage : métiers / synonymes ---
  P('Bricoleur', 'bricoleur', 'bricolage', 'Bricolage', '/bricolage'),
  P('Homme toutes mains', 'homme-toutes-mains', 'bricolage', 'Bricolage', '/bricolage'),
  P('Homme à tout faire', 'homme-a-tout-faire', 'bricolage', 'Bricolage', '/bricolage'),
  P('Monteur de meubles', 'monteur-de-meubles', 'bricolage', 'Bricolage', '/bricolage/montage-de-meubles'),
  P('Peintre en bâtiment', 'peintre-en-batiment', 'bricolage', 'Bricolage', '/bricolage/peinture-interieure'),
  P('Plombier', 'plombier', 'bricolage', 'Bricolage', '/bricolage/petits-travaux-plomberie'),
  P('Électricien', 'electricien', 'bricolage', 'Bricolage', '/bricolage/petits-travaux-electricite'),
  P('Serrurier', 'serrurier', 'bricolage', 'Bricolage', '/bricolage/serrurerie'),
  P('Poseur de papier peint', 'poseur-de-papier-peint', 'bricolage', 'Bricolage', '/bricolage/pose-papier-peint'),
  P('Technicien électroménager', 'technicien-electromenager', 'bricolage', 'Bricolage', '/bricolage/installation-electromenager'),
  P('Poseur de crédence', 'poseur-de-credence', 'bricolage', 'Bricolage', '/bricolage/pose-credence'),
  P("Poseur d'étagères", 'poseur-d-etageres', 'bricolage', 'Bricolage', '/bricolage/fixation-etageres'),
  P('Monteur IKEA', 'monteur-ikea', 'bricolage', 'Bricolage', '/bricolage/assemblage-ikea'),
  P('Poseur de tringles à rideaux', 'poseur-de-tringles-a-rideaux', 'bricolage', 'Bricolage', '/bricolage/pose-tringles-rideaux'),
  P('Poseur de porte', 'poseur-de-porte', 'bricolage', 'Bricolage', '/bricolage/remplacer-porte-poignee'),
  P('Multiservices bricolage', 'multiservices-bricolage', 'bricolage', 'Bricolage', '/bricolage'),
  P('Artisan bricoleur', 'artisan-bricoleur', 'bricolage', 'Bricolage', '/bricolage'),

  // --- Jardinage : les 16 prestations existantes ---
  P('Tonte de pelouse', 'tonte-de-pelouse', 'jardinage', 'Jardinage', '/jardinage/tonte-de-pelouse'),
  P('Taille de haie', 'taille-de-haie', 'jardinage', 'Jardinage', '/jardinage/taille-de-haie'),
  P('Débroussaillage', 'debroussaillage', 'jardinage', 'Jardinage', '/jardinage/debroussaillage'),
  P('Désherbage', 'desherbage', 'jardinage', 'Jardinage', '/jardinage/desherbage'),
  P('Élagage', 'elagage', 'jardinage', 'Jardinage', '/jardinage/elagage'),
  P('Ramassage de feuilles', 'ramassage-feuilles', 'jardinage', 'Jardinage', '/jardinage/ramassage-feuilles'),
  P('Entretien des massifs', 'entretien-massifs', 'jardinage', 'Jardinage', '/jardinage/entretien-massifs'),
  P("Arrosage pendant l'absence", 'arrosage-pendant-absence', 'jardinage', 'Jardinage', '/jardinage/arrosage-pendant-absence'),
  P('Création de potager', 'creation-potager', 'jardinage', 'Jardinage', '/jardinage/creation-potager'),
  P('Plantation de fleurs et arbustes', 'plantation-fleurs-arbustes', 'jardinage', 'Jardinage', '/jardinage/plantation-fleurs-arbustes'),
  P('Entretien du potager ou du verger', 'entretien-potager-verger', 'jardinage', 'Jardinage', '/jardinage/entretien-potager-verger'),
  P('Aménagement de jardin', 'amenagement-du-jardin', 'jardinage', 'Jardinage', '/jardinage/amenagement-du-jardin'),
  P('Montage de pergola, abri de jardin, serre', 'montage-pergola-abri-serre', 'jardinage', 'Jardinage', '/jardinage/montage-pergola-abri-serre'),
  P("Installation d'arrosage automatique", 'installation-arrosage-automatique', 'jardinage', 'Jardinage', '/jardinage/installation-arrosage-automatique'),
  P('Nettoyage de terrasse', 'nettoyage-terrasse', 'jardinage', 'Jardinage', '/jardinage/nettoyage-terrasse'),
  P('Entretien de piscine', 'entretien-piscine', 'jardinage', 'Jardinage', '/jardinage/entretien-piscine'),
  // --- Jardinage : métiers / synonymes ---
  P('Jardinier', 'jardinier', 'jardinage', 'Jardinage', '/jardinage'),
  P('Jardinier paysagiste', 'jardinier-paysagiste', 'jardinage', 'Jardinage', '/jardinage/amenagement-du-jardin'),
  P('Paysagiste', 'paysagiste', 'jardinage', 'Jardinage', '/jardinage/amenagement-du-jardin'),
  P('Élagueur', 'elagueur', 'jardinage', 'Jardinage', '/jardinage/elagage'),
  P('Débroussailleur', 'debroussailleur', 'jardinage', 'Jardinage', '/jardinage/debroussaillage'),
  P('Tondeur de pelouse', 'tondeur-de-pelouse', 'jardinage', 'Jardinage', '/jardinage/tonte-de-pelouse'),
  P('Tailleur de haie', 'tailleur-de-haie', 'jardinage', 'Jardinage', '/jardinage/taille-de-haie'),
  P('Entretien espaces verts', 'entretien-espaces-verts', 'jardinage', 'Jardinage', '/jardinage'),
  P("Jardinier d'entretien", 'jardinier-d-entretien', 'jardinage', 'Jardinage', '/jardinage'),
  P("Installateur d'arrosage automatique", 'installateur-arrosage-automatique', 'jardinage', 'Jardinage', '/jardinage/installation-arrosage-automatique'),
  P('Entretien de jardin', 'entretien-de-jardin', 'jardinage', 'Jardinage', '/jardinage'),
  P('Aide à la création de potager', 'aide-creation-potager', 'jardinage', 'Jardinage', '/jardinage/creation-potager'),

  // --- Ménage : les 13 prestations existantes ---
  P('Ménage à domicile', 'menage-a-domicile', 'menage', 'Ménage', '/menage/menage-a-domicile'),
  P('Ménage de printemps', 'menage-de-printemps', 'menage', 'Ménage', '/menage/menage-de-printemps'),
  P("Ménage d'état des lieux", 'menage-etat-des-lieux', 'menage', 'Ménage', '/menage/menage-etat-des-lieux'),
  P('Ménage de location saisonnière', 'menage-location-saisonniere', 'menage', 'Ménage', '/menage/menage-location-saisonniere'),
  P('Ménage après un événement', 'menage-apres-evenement', 'menage', 'Ménage', '/menage/menage-apres-evenement'),
  P('Nettoyage de vitres', 'nettoyage-vitres', 'menage', 'Ménage', '/menage/nettoyage-vitres'),
  P('Repassage', 'repassage', 'menage', 'Ménage', '/menage/repassage'),
  P('Aide au rangement', 'aide-au-rangement', 'menage', 'Ménage', '/menage/aide-au-rangement'),
  P('Nettoyage après travaux', 'nettoyage-apres-travaux', 'menage', 'Ménage', '/menage/nettoyage-apres-travaux'),
  P('Nettoyage de fin de bail', 'nettoyage-fin-de-bail', 'menage', 'Ménage', '/menage/nettoyage-fin-de-bail'),
  P('Nettoyage électroménager', 'nettoyage-electromenager', 'menage', 'Ménage', '/menage/nettoyage-electromenager'),
  P('Nettoyage textile', 'nettoyage-textile', 'menage', 'Ménage', '/menage/nettoyage-textile'),
  P('Nettoyage de logement insalubre', 'nettoyage-logement-insalubre', 'menage', 'Ménage', '/menage/nettoyage-logement-insalubre'),
  // --- Ménage : métiers / synonymes ---
  P('Femme de ménage', 'femme-de-menage', 'menage', 'Ménage', '/menage'),
  P("Agent d'entretien", 'agent-d-entretien', 'menage', 'Ménage', '/menage'),
  P('Aide ménagère', 'aide-menagere', 'menage', 'Ménage', '/menage'),
  P('Aide-ménagère à domicile', 'aide-menagere-a-domicile', 'menage', 'Ménage', '/menage/menage-a-domicile'),
  P('Repasseuse', 'repasseuse', 'menage', 'Ménage', '/menage/repassage'),
  P('Nettoyeur de vitres', 'nettoyeur-de-vitres', 'menage', 'Ménage', '/menage/nettoyage-vitres'),
  P('Nettoyage professionnel', 'nettoyage-professionnel', 'menage', 'Ménage', '/menage'),
  P('Femme de ménage location saisonnière', 'femme-de-menage-location-saisonniere', 'menage', 'Ménage', '/menage/menage-location-saisonniere'),
  P('Nettoyeur fin de bail', 'nettoyeur-fin-de-bail', 'menage', 'Ménage', '/menage/nettoyage-fin-de-bail'),

  // --- Piscine : les 7 prestations existantes ---
  P('Entretien régulier de piscine', 'entretien-regulier', 'piscine', 'Piscine', '/piscine/entretien-regulier'),
  P('Remise en état de piscine', 'remise-en-etat', 'piscine', 'Piscine', '/piscine/remise-en-etat'),
  P('Traitement et hivernage de piscine', 'traitement-hivernage', 'piscine', 'Piscine', '/piscine/traitement-hivernage'),
  P('Nettoyage du bassin et des skimmers', 'nettoyage-bassin-skimmers', 'piscine', 'Piscine', '/piscine/nettoyage-bassin-skimmers'),
  P('Contrôle du robot de piscine', 'controle-robot-piscine', 'piscine', 'Piscine', '/piscine/controle-robot-piscine'),
  P('Peinture de bassin', 'peinture-bassin', 'piscine', 'Piscine', '/piscine/peinture-bassin'),
  P('Réparation de fissures ou de carrelage', 'reparation-fissures-carrelage', 'piscine', 'Piscine', '/piscine/reparation-fissures-carrelage'),
  // --- Piscine : métiers / synonymes ---
  P('Pisciniste', 'pisciniste', 'piscine', 'Piscine', '/piscine'),
  P('Technicien piscine', 'technicien-piscine', 'piscine', 'Piscine', '/piscine/entretien-regulier'),
  P('Nettoyage de piscine', 'nettoyage-de-piscine', 'piscine', 'Piscine', '/piscine/nettoyage-bassin-skimmers'),
  P('Hivernage piscine', 'hivernage-piscine', 'piscine', 'Piscine', '/piscine/traitement-hivernage'),
  P('Réparation piscine', 'reparation-piscine', 'piscine', 'Piscine', '/piscine/reparation-fissures-carrelage'),
  P('Peintre de piscine', 'peintre-de-piscine', 'piscine', 'Piscine', '/piscine/peinture-bassin'),

  // --- Conciergerie : les 11 prestations existantes ---
  P('Surveillance de résidence secondaire', 'surveillance-residence-secondaire', 'conciergerie', 'Conciergerie', '/conciergerie/surveillance-residence-secondaire'),
  P('Remise et gestion des clés', 'remise-gestion-cles', 'conciergerie', 'Conciergerie', '/conciergerie/remise-gestion-cles'),
  P('Accueil des voyageurs', 'accueil-voyageurs', 'conciergerie', 'Conciergerie', '/conciergerie/accueil-voyageurs'),
  P("État des lieux d'entrée et de sortie", 'etat-des-lieux-entree-sortie', 'conciergerie', 'Conciergerie', '/conciergerie/etat-des-lieux-entree-sortie'),
  P('Réception de colis et de courrier', 'reception-colis-courrier', 'conciergerie', 'Conciergerie', '/conciergerie/reception-colis-courrier'),
  P('Relevé de compteurs', 'releve-compteurs', 'conciergerie', 'Conciergerie', '/conciergerie/releve-compteurs'),
  P("Ouverture pour un artisan ou un prestataire", 'ouverture-artisan-prestataire', 'conciergerie', 'Conciergerie', '/conciergerie/ouverture-artisan-prestataire'),
  P('Coordination de petits travaux', 'coordination-petits-travaux', 'conciergerie', 'Conciergerie', '/conciergerie/coordination-petits-travaux'),
  P('Aération et entretien entre deux séjours', 'aeration-entretien-entre-sejours', 'conciergerie', 'Conciergerie', '/conciergerie/aeration-entretien-entre-sejours'),
  P('Gestion complète', 'gestion-complete', 'conciergerie', 'Conciergerie', '/conciergerie/gestion-complete'),
  P('Buanderie-Pressing', 'buanderie-pressing', 'conciergerie', 'Conciergerie', '/conciergerie/buanderie-pressing'),
  // --- Conciergerie : métiers / synonymes ---
  P('Concierge', 'concierge', 'conciergerie', 'Conciergerie', '/conciergerie'),
  P('Gardien de propriété', 'gardien-de-propriete', 'conciergerie', 'Conciergerie', '/conciergerie/surveillance-residence-secondaire'),
  P('Conciergerie Airbnb', 'conciergerie-airbnb', 'conciergerie', 'Conciergerie', '/conciergerie/gestion-complete'),
  P('Gestionnaire de location saisonnière', 'gestionnaire-location-saisonniere', 'conciergerie', 'Conciergerie', '/conciergerie/gestion-complete'),
  P('Accueil voyageurs Airbnb', 'accueil-voyageurs-airbnb', 'conciergerie', 'Conciergerie', '/conciergerie/accueil-voyageurs'),
  P('Gestion des clés', 'gestion-des-cles', 'conciergerie', 'Conciergerie', '/conciergerie/remise-gestion-cles'),
  P('Conciergerie résidence secondaire', 'conciergerie-residence-secondaire', 'conciergerie', 'Conciergerie', '/conciergerie/surveillance-residence-secondaire'),
];

export const METIERS_BY_SLUG = Object.fromEntries(METIERS.map((m) => [m.slug, m]));
