// Curated list of major French cities for local SEO landing pages
// (/services/[category]/[city]). Kept as a static list rather than a live
// geocoding lookup so the page set is stable and predictable for the sitemap.
export const SEO_CITIES = [
  { name: 'Paris', slug: 'paris', region: 'Île-de-France' },
  { name: 'Marseille', slug: 'marseille', region: "Provence-Alpes-Côte d'Azur" },
  { name: 'Lyon', slug: 'lyon', region: 'Auvergne-Rhône-Alpes' },
  { name: 'Toulouse', slug: 'toulouse', region: 'Occitanie' },
  { name: 'Nice', slug: 'nice', region: "Provence-Alpes-Côte d'Azur" },
  { name: 'Nantes', slug: 'nantes', region: 'Pays de la Loire' },
  { name: 'Montpellier', slug: 'montpellier', region: 'Occitanie' },
  { name: 'Strasbourg', slug: 'strasbourg', region: 'Grand Est' },
  { name: 'Bordeaux', slug: 'bordeaux', region: 'Nouvelle-Aquitaine' },
  { name: 'Lille', slug: 'lille', region: 'Hauts-de-France' },
  { name: 'Rennes', slug: 'rennes', region: 'Bretagne' },
  { name: 'Reims', slug: 'reims', region: 'Grand Est' },
  { name: 'Le Havre', slug: 'le-havre', region: 'Normandie' },
  { name: 'Saint-Étienne', slug: 'saint-etienne', region: 'Auvergne-Rhône-Alpes' },
  { name: 'Toulon', slug: 'toulon', region: "Provence-Alpes-Côte d'Azur" },
  { name: 'Grenoble', slug: 'grenoble', region: 'Auvergne-Rhône-Alpes' },
  { name: 'Dijon', slug: 'dijon', region: 'Bourgogne-Franche-Comté' },
  { name: 'Angers', slug: 'angers', region: 'Pays de la Loire' },
  { name: 'Nîmes', slug: 'nimes', region: 'Occitanie' },
  { name: 'Villeurbanne', slug: 'villeurbanne', region: 'Auvergne-Rhône-Alpes' },
  { name: 'Clermont-Ferrand', slug: 'clermont-ferrand', region: 'Auvergne-Rhône-Alpes' },
  { name: 'Le Mans', slug: 'le-mans', region: 'Pays de la Loire' },
  { name: 'Aix-en-Provence', slug: 'aix-en-provence', region: "Provence-Alpes-Côte d'Azur" },
  { name: 'Brest', slug: 'brest', region: 'Bretagne' },
  { name: 'Tours', slug: 'tours', region: 'Centre-Val de Loire' },
  { name: 'Amiens', slug: 'amiens', region: 'Hauts-de-France' },
  { name: 'Limoges', slug: 'limoges', region: 'Nouvelle-Aquitaine' },
  { name: 'Annecy', slug: 'annecy', region: 'Auvergne-Rhône-Alpes' },
  { name: 'Perpignan', slug: 'perpignan', region: 'Occitanie' },
  { name: 'Metz', slug: 'metz', region: 'Grand Est' },
  { name: 'Besançon', slug: 'besancon', region: 'Bourgogne-Franche-Comté' },
  { name: 'Orléans', slug: 'orleans', region: 'Centre-Val de Loire' },
  { name: 'Rouen', slug: 'rouen', region: 'Normandie' },
  { name: 'Mulhouse', slug: 'mulhouse', region: 'Grand Est' },
  { name: 'Caen', slug: 'caen', region: 'Normandie' },
  { name: 'Nancy', slug: 'nancy', region: 'Grand Est' },
  { name: 'Avignon', slug: 'avignon', region: "Provence-Alpes-Côte d'Azur" },
  { name: 'Béziers', slug: 'beziers', region: 'Occitanie' },
  { name: 'Montauban', slug: 'montauban', region: 'Occitanie' },
  { name: 'Narbonne', slug: 'narbonne', region: 'Occitanie' },
];
